#!/usr/bin/env php
<?php

require_once __DIR__.'/AppTestKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use EDC\CommandSchedulerBundle\Tests\AppTestKernel;

$kernel = new AppTestKernel('test', true);
$kernel->boot();

$app = new Application($kernel);
$app->run();